name: seeker_flutter
description: "A Flutter conversion of the Seeker React Native app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5 # For value equality in Bloc states/models
  intl: ^0.19.0 # For date formatting, etc.

  # State Management
  flutter_bloc: ^8.1.5 # BLoC pattern implementation
  bloc: ^8.1.4

  # Routing
  go_router: ^14.0.0 # Declarative routing

  # Networking
  http: ^1.2.1 # HTTP requests

  # Firebase
  firebase_core: ^2.30.1 # Required for Firebase integration
  firebase_auth: ^4.19.4 # Firebase Authentication

  # Storage
  flutter_secure_storage: ^9.1.1 # Secure storage for tokens

  # Utilities
  logger: ^2.2.0 # Logging utility
  # json_annotation: ^4.8.1 # For JSON serialization (optional, if using build_runner)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  # build_runner: ^2.4.9 # Code generator (optional, for json_serializable)
  # json_serializable: ^6.7.1 # JSON serialization generator (optional)


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
