// GENERATED CODE - MANUALLY IMPLEMENTED
// Would normally be generated by build_runner

part of 'profile_models.dart';

// --- Enum Conversions --- //

const _$EducationLevelEnumMap = {
  EducationLevel.tenth: '10th',
  EducationLevel.twelfth: '12th',
  EducationLevel.diploma: 'Diploma',
  EducationLevel.iti: 'ITI',
  EducationLevel.graduate: 'Graduate',
  EducationLevel.postGraduate: 'Post Graduate',
  EducationLevel.doctorate: 'Doctorate',
};

const _$GenderEnumMap = {
  Gender.male: 'Male',
  Gender.female: 'Female',
  Gender.other: 'Other',
};

const _$ProficiencyLevelEnumMap = {
  ProficiencyLevel.beginner: 'Beginner',
  ProficiencyLevel.intermediate: 'Intermediate',
  ProficiencyLevel.advanced: 'Advanced',
  ProficiencyLevel.native: 'Native',
};

const _$VerificationStatusEnumMap = {
  VerificationStatus.pending: 'Pending',
  VerificationStatus.verified: 'Verified',
  VerificationStatus.rejected: 'Rejected',
};

const _$JobTypeEnumMap = {
  JobType.fullTime: 'Full-time',
  JobType.partTime: 'Part-time',
  JobType.contract: 'Contract',
  JobType.internship: 'Internship',
  JobType.freelance: 'Freelance',
};

const _$WorkLocationTypeEnumMap = {
  WorkLocationType.onsite: 'Onsite',
  WorkLocationType.remote: 'Remote',
  WorkLocationType.hybrid: 'Hybrid',
};

// Helper functions for enum conversion
T? _$enumDecodeNullable<T>(
  Map<T, dynamic> enumValues,
  dynamic source, {
  T? unknownValue,
}) {
  if (source == null) {
    return null;
  }
  return _$enumDecode<T>(enumValues, source, unknownValue: unknownValue);
}

T _$enumDecode<T>(
  Map<T, dynamic> enumValues,
  dynamic source, {
  T? unknownValue,
}) {
  if (source == null) {
    throw ArgumentError('A value must be provided. Supported values: '
        '${enumValues.values.join(', ')}');
  }

  return enumValues.entries.singleWhere(
    (e) => e.value == source,
    orElse: () {
      if (unknownValue == null) {
        throw ArgumentError('`$source` is not one of the supported values: '
            '${enumValues.values.join(', ')}');
      }
      return MapEntry(unknownValue, enumValues.values.first);
    },
  ).key;
}

// --- Model Serialization --- //

// Address Model
AddressModel _$AddressModelFromJson(Map<String, dynamic> json) => AddressModel(
    street: json['street'] as String?,
    city: json['city'] as String?,
    state: json['state'] as String?,
    postalCode: json['postal_code'] as String?,
    country: json['country'] as String?,
    isCurrent: json['is_current'] as bool?,
  );

Map<String, dynamic> _$AddressModelToJson(AddressModel instance) {
  final val = <String, dynamic>{};

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('street', instance.street);
  writeNotNull('city', instance.city);
  writeNotNull('state', instance.state);
  writeNotNull('postal_code', instance.postalCode);
  writeNotNull('country', instance.country);
  writeNotNull('is_current', instance.isCurrent);
  return val;
}

// Personal Details Model
PersonalDetailsModel _$PersonalDetailsModelFromJson(Map<String, dynamic> json) =>
    PersonalDetailsModel(
      name: json['name'] as String?,
      fatherName: json['father_name'] as String?,
      motherName: json['mother_name'] as String?,
      gender: json['gender'] as String?,
      dob: json['dob'] == null ? null : DateTime.parse(json['dob'] as String),
      guardianName: json['guardian_name'] as String?,
      profilePictureUrl: json['profile_picture_url'] as String?,
    );

Map<String, dynamic> _$PersonalDetailsModelToJson(PersonalDetailsModel instance) {
  final val = <String, dynamic>{};

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('name', instance.name);
  writeNotNull('father_name', instance.fatherName);
  writeNotNull('mother_name', instance.motherName);
  writeNotNull('gender', instance.gender);
  writeNotNull('dob', instance.dob?.toIso8601String());
  writeNotNull('guardian_name', instance.guardianName);
  writeNotNull('profile_picture_url', instance.profilePictureUrl);
  return val;
}

// Contact Details Model
ContactDetailsModel _$ContactDetailsModelFromJson(Map<String, dynamic> json) =>
    ContactDetailsModel(
      primaryMobile: json['primary_mobile'] as String?,
      secondaryMobile: json['secondary_mobile'] as String?,
      email: json['email'] as String?,
      permanentAddress: json['permanent_address'] == null
          ? null
          : AddressModel.fromJson(
              json['permanent_address'] as Map<String, dynamic>),
      currentAddress: json['current_address'] == null
          ? null
          : AddressModel.fromJson(
              json['current_address'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$ContactDetailsModelToJson(ContactDetailsModel instance) {
  final val = <String, dynamic>{};

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('primary_mobile', instance.primaryMobile);
  writeNotNull('secondary_mobile', instance.secondaryMobile);
  writeNotNull('email', instance.email);
  writeNotNull('permanent_address', instance.permanentAddress?.toJson());
  writeNotNull('current_address', instance.currentAddress?.toJson());
  return val;
}
